---
- name: Ensure Git is installed
  package:
    name: git-all
    state: present

- name: Ensure user email is configured
  git_config:
    name: user.email
    value: '{{ git_user_email }}'

- name: Ensure user name is configured
  git_config:
    name: user.name
    value: '{{ git_user_name }}'
